# Generated by Django 4.2.1 on 2023-05-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssh_connect',
            name='user',
            field=models.CharField(max_length=40, null=True, verbose_name='Username Host ssh'),
        ),
    ]
