# Generated by Django 4.0.3 on 2023-06-04 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_ssh_connect_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peer_monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, null=True, verbose_name='Nombre de cliente')),
                ('publicKey', models.CharField(max_length=50, null=True, unique=True, verbose_name='Peer')),
                ('endpoint', models.CharField(max_length=50, null=True, verbose_name='Endpoint')),
                ('transfer', models.CharField(max_length=50, null=True, verbose_name='Transferencia')),
                ('latest_handshake', models.CharField(max_length=50, null=True, verbose_name='Tiempo conexion')),
                ('allowedIps', models.GenericIPAddressField(verbose_name='ip del cliente')),
            ],
        ),
    ]
