# Generated by Django 4.2.1 on 2023-06-11 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_alter_peer_monitor_publickey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peer_monitor',
            name='nombre',
        ),
    ]
