# Generated by Django 4.2.1 on 2023-06-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_peer_cliente_server_id_peer_cliente_user_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer_server',
            name='privateKey',
            field=models.CharField(max_length=50, null=True, verbose_name='clave privada'),
        ),
    ]
